# fly.toml app configuration file generated for business-test-david-raygosa on 2023-05-27T16:19:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "business-test-david-raygosa"
primary_region = "qro"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true